-- Bài tập 1
-- QLKH - Phần I Câu 1
create database QUANLIKHACHHANG;
use QUANLIKHACHHANG;

CREATE TABLE KHACHHANG
(
	MAKH char(4),
	HOTEN varchar(40),
	DCHI varchar(50),
	SODT varchar(20),
	NGSINH datetime,
	NGDK datetime,
	DOANHSO decimal(15,2)
);

CREATE TABLE NHANVIEN
(
	MANV char(4),
	HOTEN varchar(40),
	SODT varchar(20),
	NGVL datetime
);

CREATE TABLE SANPHAM
(
	MASP char(4),
	TENSP varchar(40),
	DVT varchar(20),
	NUOCSX varchar(40),
	GIA decimal(15,2)
);

CREATE TABLE HOADON
(
	SOHD int,
	NGHD datetime,
	MAKH char(4),
	MANV char(4),
	TRIGIA decimal(15,2)
);

CREATE TABLE CTHD
(
	SOHD int,
	MASP char(4),
	SL int
);

ALTER TABLE KHACHHANG
ADD PRIMARY KEY (MAKH);

ALTER TABLE NHANVIEN
ADD PRIMARY KEY (MANV);

ALTER TABLE SANPHAM
ADD PRIMARY KEY (MASP);

ALTER TABLE HOADON
ADD PRIMARY KEY (SOHD);

ALTER TABLE CTHD
ADD PRIMARY KEY (SOHD,MASP);

ALTER TABLE HOADON
ADD FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH);

ALTER TABLE HOADON
ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV);

ALTER TABLE CTHD
ADD FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD);

ALTER TABLE CTHD
ADD FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP);

ALTER TABLE HOADON
ADD FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH);

-- QLHV - Phần I Câu 1
create database QUANLIHOCVU;
use QUANLIHOCVU;

CREATE TABLE KHOA (
	MAKHOA varchar(4) PRIMARY KEY,
	TENKHOA varchar(40),
	NGTLAP datetime,
	TRGKHOA char(4)
);

CREATE TABLE MONHOC (
	MAMH varchar(10) PRIMARY KEY,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4)
);

CREATE TABLE DIEUKIEN (
	MAMH varchar(10),
	MAMH_TRUOC varchar(10),
	PRIMARY KEY(MAMH, MAMH_TRUOC)
);

CREATE TABLE GIAOVIEN (
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH datetime,
	NGVL datetime,
	HESO numeric(4, 2),
	MUCLUONG decimal(15,2),
	MAKHOA varchar(4)
);

CREATE TABLE LOP (
	MALOP char(3) PRIMARY KEY,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4)
);

CREATE TABLE HOCVIEN (
	MAHV char(5) PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	NGSINH datetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3)
);

CREATE TABLE GIANGDAY (
	MALOP char(3),
	MAMH varchar(10),
	MAGV char(4),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY datetime,
	DENNGAY datetime,
	PRIMARY KEY(MALOP, MAMH)
);

CREATE TABLE KETQUATHI (
	MAHV char(5),
	MAMH varchar(10),
	LANTHI tinyint,
	NGTHI datetime,
	DIEM numeric(4, 2),
	KQUA varchar(10),
	PRIMARY KEY(MAHV, MAMH, LANTHI)
);

ALTER TABLE KHOA
ADD FOREIGN KEY(TRGKHOA) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE MONHOC
ADD FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE DIEUKIEN
ADD FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE DIEUKIEN
ADD FOREIGN KEY(MAMH_TRUOC) REFERENCES MONHOC(MAMH);

ALTER TABLE GIAOVIEN
ADD FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE LOP
ADD FOREIGN KEY(TRGLOP) REFERENCES HOCVIEN(MAHV);
	
 ALTER TABLE LOP
ADD FOREIGN KEY(MAGVCN) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE HOCVIEN
ADD FOREIGN KEY(MALOP) REFERENCES LOP(MALOP);

ALTER TABLE GIANGDAY
ADD FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);
	
ALTER TABLE GIANGDAY
ADD FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV);
	
ALTER TABLE GIANGDAY
ADD FOREIGN KEY(MALOP) REFERENCES LOP(MALOP);

ALTER TABLE KETQUATHI
ADD FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV);

ALTER TABLE GIANGDAY
ADD FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH);

-- Thêm vào 3 thuộc tính
ALTER TABLE HOCVIEN
ADD GHICHU varchar(20);

ALTER TABLE HOCVIEN
ADD DIEMTB numeric(4,2);

ALTER TABLE HOCVIEN
ADD XEPLOAI varchar(5);

-- Bài tập 2 
use QUANLIKHACHHANG;

ALTER TABLE SANPHAM
ADD GHICHU varchar(20);

ALTER TABLE KHACHHANG
ADD LOAIKH tinyint;

